on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Tencent Cloudbase Github Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
      - name: Deploy static to Tencent CloudBase
        shell: bash
        run: |
          sudo npm i -g @cloudbase/cli
          tcb login --apiKeyId ${{ secrets.SECRET_ID }} --apiKey ${{ secrets.SECRET_KEY }}
          tcb hosting deploy index.html -e ${{ secrets.ENV_ID }} -r ap-guangzhou